src/objects/Code_Variables__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <type>TextArea</type>
    </fields>
    <label>Code Variables</label>
</CustomObject>

src/objects/Dev_Tool_Config__c.object
<CustomObject>
    <fields>
        <fullName>Page_Name__c</fullName>
        <label>Page Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Dev Tool Config</label>
    <nameField>
        <label>Tool name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dev Tool Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PostInstallClass.cls
//global class PostInstallClass implements InstallHandler
//{
public class PostInstallClass
{
	//global void onInstall(InstallContext context)
	public static void onInstall()
	{
		//if(context.previousVersion() == null)
		//{
		List<Dev_Tool_Config__c> allRecords = new List<Dev_Tool_Config__c>([SELECT Id, name FROM Dev_Tool_Config__c]);
		List<Code_Variables__c> newCodeVariableRecords = Code_Variables__c.getAll().values();
		if(allRecords.isEmpty())
		{
			Id toolRecordType = [SELECT Id FROM RecordType WHERE Name='Dev Tool'].Id;
			Dev_Tool_Config__c xmlParser = new Dev_Tool_Config__c(Name='XML Parser', Page_Name__c='AppirioXMLParser', Sort_Order__c=1, RecordTypeId=toolRecordType);
			Dev_Tool_Config__c awesomeExtractor = new Dev_Tool_Config__c(Name='Awesome Extractor', Sort_Order__c=2, RecordTypeId=toolRecordType);
			Dev_Tool_Config__c customScheduler = new Dev_Tool_Config__c(Name='Custom Scheduler', Sort_Order__c=3, RecordTypeId=toolRecordType);
			List<Dev_Tool_Config__c> allDevToolsToCreate = new List<Dev_Tool_Config__c>{xmlParser, awesomeExtractor, customScheduler};
			insert allDevToolsToCreate;
		}
		if(newCodeVariableRecords.isEmpty())
		{
			// create code variable records here too
			Code_Variables__c xmlParserNumCols = new Code_Variables__c(Name='XMLParserNumCols', Value__c='80');
			Code_Variables__c xmlParserNumRows = new Code_Variables__c(Name='XMLParserNumRows',Value__c='15');
			List<Code_Variables__c> allCodeVariablesToCreate = new List<Code_Variables__c>{xmlParserNumCols, xmlParserNumRows};
			insert allCodeVariablesToCreate;
		}
	}
}