src/objects/Dev_Tool_Config__c.object
<CustomObject>
    <fields>
        <fullName>Page_Name__c</fullName>
        <label>Page Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>img_url__c</fullName>
        <label>img url</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Dev Tool Config</label>
    <nameField>
        <label>Tool name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dev Tool Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AppirioToolIndexController.cls
//
// (c) 2015 Appirio, Inc.
//
// Controller for index page of dev tools
//
// 5 Mar 2015 Leo Alves     Original

public class AppirioToolIndexController {
    // properties
    public List<Dev_Tool_Config__c> devTools {
        get {
            if (devTools == null)
                devTools = [SELECT name, page_name__c, img_url__c
                            FROM Dev_Tool_Config__c ORDER BY sort_order__c];
            return devTools;
        }
        private set;
    }
    
    // constructor
    public AppirioToolIndexController(){}
}